travis:
  secure:
    BINSTAR_TOKEN: NZoFx9jbAZrutgVI83BZTG9f4atgGN8KExcjhnzeIthhb4Ap2wGOiecktW0rVUMVK6dQRs6vi4zAckhcRsl+crk8hZ/vKcWI2+Jq2F4OP+tlLyNHVD66KQgNYsoYqe26NK1blnpGdGDFak52Xfz9J0GFF/LTjTMtY+y64UasS/5iETZg3DmL7dwL6VwlpdpE/V3O1tODQuEmPM2lJ3QGAVoyelw9upK3A633NLLwisaV3AVVCfSrl/d3I8QyB8GLbQoeoBABPxvxjMxMYFLqWJSxIcO+8LOkMMTV/FKmp/+yoNS3j6log+bEe/MNFNNfA83Vxy9cdQmwr/G07J4YYJuFKULwdwyXPnim50mrO0Sv/lp6kHc6LzBknUqW13oXHPTFqMggqf+czxlTxm1gRAER2j1Z27QyTvRIFY0A3ZdZi77KfIj+cREzT4U8Hw5Hf600CRPw8t5WYrtaNp1/ujG9BaqgtYlFhOJz/ktfDnTU4voU+xVv7qJ0wsPQIsp1Fc6zhj3wuSvc7XQNvxFIGk0MrpM6ovL8Qxi25nH+Rmhu/wkKhK6qjnrIyUXFJWov3w4LQlEFBXedj7PiZEK0j/StU1Z1KDiaXsctcu71gGd4k+Fqxsss/Ofk0OvyrfGA1zJio0leBNhqclXJKmw4S5hy937cjTi8K/+mwVt24go=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
